// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export type ImageVariant = { src: string; width: number };
export type ImageEntry = { width: number; height: number; variants: readonly ImageVariant[] };

export const images = {
  "products/ales": {
    "width": 1200,
    "height": 814,
    "variants": [
      {
        "src": "/images/products/ales-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/ales-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/ales-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/amour": {
    "width": 1200,
    "height": 848,
    "variants": [
      {
        "src": "/images/products/amour-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/amour-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/amour-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/bioactive-b12": {
    "width": 1200,
    "height": 866,
    "variants": [
      {
        "src": "/images/products/bioactive-b12-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/bioactive-b12-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/bioactive-b12-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/breez": {
    "width": 995,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/breez-400.webp",
        "width": 332
      },
      {
        "src": "/images/products/breez-800.webp",
        "width": 663
      },
      {
        "src": "/images/products/breez-1200.webp",
        "width": 995
      }
    ]
  },
  "products/colochiqan": {
    "width": 1200,
    "height": 846,
    "variants": [
      {
        "src": "/images/products/colochiqan-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/colochiqan-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/colochiqan-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/cresuva": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/cresuva-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/cresuva-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/cresuva-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/dozile": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/dozile-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/dozile-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/dozile-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/emperor": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/emperor-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/emperor-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/emperor-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/etoria": {
    "width": 892,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/etoria-400.webp",
        "width": 297
      },
      {
        "src": "/images/products/etoria-800.webp",
        "width": 595
      },
      {
        "src": "/images/products/etoria-1200.webp",
        "width": 892
      }
    ]
  },
  "products/evin": {
    "width": 1034,
    "height": 642,
    "variants": [
      {
        "src": "/images/products/evin-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/evin-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/evin-1034.webp",
        "width": 1034
      }
    ]
  },
  "products/extenda": {
    "width": 1200,
    "height": 1075,
    "variants": [
      {
        "src": "/images/products/extenda-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/extenda-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/extenda-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/ferroqan": {
    "width": 734,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/ferroqan-400.webp",
        "width": 245
      },
      {
        "src": "/images/products/ferroqan-800.webp",
        "width": 489
      },
      {
        "src": "/images/products/ferroqan-1200.webp",
        "width": 734
      }
    ]
  },
  "products/gastop": {
    "width": 1200,
    "height": 890,
    "variants": [
      {
        "src": "/images/products/gastop-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/gastop-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/gastop-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/melaton": {
    "width": 1200,
    "height": 803,
    "variants": [
      {
        "src": "/images/products/melaton-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/melaton-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/melaton-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/moximax": {
    "width": 741,
    "height": 741,
    "variants": [
      {
        "src": "/images/products/moximax-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/moximax-741.webp",
        "width": 741
      }
    ]
  },
  "products/pymol-extra": {
    "width": 1200,
    "height": 897,
    "variants": [
      {
        "src": "/images/products/pymol-extra-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/pymol-extra-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/pymol-extra-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/pymol": {
    "width": 1200,
    "height": 897,
    "variants": [
      {
        "src": "/images/products/pymol-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/pymol-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/pymol-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/stay-up": {
    "width": 1200,
    "height": 872,
    "variants": [
      {
        "src": "/images/products/stay-up-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/stay-up-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/stay-up-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/superdal": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/superdal-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/superdal-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/superdal-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/supervit-c-plus": {
    "width": 1011,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/supervit-c-plus-400.webp",
        "width": 337
      },
      {
        "src": "/images/products/supervit-c-plus-800.webp",
        "width": 674
      },
      {
        "src": "/images/products/supervit-c-plus-1200.webp",
        "width": 1011
      }
    ]
  },
  "products/supervit-c": {
    "width": 1011,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/supervit-c-400.webp",
        "width": 337
      },
      {
        "src": "/images/products/supervit-c-800.webp",
        "width": 674
      },
      {
        "src": "/images/products/supervit-c-1200.webp",
        "width": 1011
      }
    ]
  },
  "products/supervit-max": {
    "width": 768,
    "height": 1037,
    "variants": [
      {
        "src": "/images/products/supervit-max-400.webp",
        "width": 296
      },
      {
        "src": "/images/products/supervit-max-800.webp",
        "width": 592
      },
      {
        "src": "/images/products/supervit-max-1037.webp",
        "width": 768
      }
    ]
  },
  "products/superzinc-plus": {
    "width": 892,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/superzinc-plus-400.webp",
        "width": 297
      },
      {
        "src": "/images/products/superzinc-plus-800.webp",
        "width": 595
      },
      {
        "src": "/images/products/superzinc-plus-1200.webp",
        "width": 892
      }
    ]
  },
  "products/superzinc": {
    "width": 1089,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/superzinc-400.webp",
        "width": 363
      },
      {
        "src": "/images/products/superzinc-800.webp",
        "width": 726
      },
      {
        "src": "/images/products/superzinc-1200.webp",
        "width": 1089
      }
    ]
  },
  "products/vertiloc": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/vertiloc-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/vertiloc-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/vertiloc-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/xaro": {
    "width": 1200,
    "height": 1200,
    "variants": [
      {
        "src": "/images/products/xaro-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/xaro-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/xaro-1200.webp",
        "width": 1200
      }
    ]
  },
  "products/zeeto": {
    "width": 1200,
    "height": 790,
    "variants": [
      {
        "src": "/images/products/zeeto-400.webp",
        "width": 400
      },
      {
        "src": "/images/products/zeeto-800.webp",
        "width": 800
      },
      {
        "src": "/images/products/zeeto-1200.webp",
        "width": 1200
      }
    ]
  },
  "facility/building-2": {
    "width": 2400,
    "height": 1753,
    "variants": [
      {
        "src": "/images/facility/building-2-640.webp",
        "width": 640
      },
      {
        "src": "/images/facility/building-2-1024.webp",
        "width": 1024
      },
      {
        "src": "/images/facility/building-2-1600.webp",
        "width": 1600
      },
      {
        "src": "/images/facility/building-2-2400.webp",
        "width": 2400
      }
    ]
  },
  "facility/building": {
    "width": 2400,
    "height": 2400,
    "variants": [
      {
        "src": "/images/facility/building-640.webp",
        "width": 640
      },
      {
        "src": "/images/facility/building-1024.webp",
        "width": 1024
      },
      {
        "src": "/images/facility/building-1600.webp",
        "width": 1600
      },
      {
        "src": "/images/facility/building-2400.webp",
        "width": 2400
      }
    ]
  },
  "facility/cleanroom": {
    "width": 981,
    "height": 817,
    "variants": [
      {
        "src": "/images/facility/cleanroom-640.webp",
        "width": 640
      },
      {
        "src": "/images/facility/cleanroom-981.webp",
        "width": 981
      }
    ]
  },
  "brand/logo-reversed": {
    "width": 2004,
    "height": 1468,
    "variants": [
      {
        "src": "/images/brand/logo-reversed-200.webp",
        "width": 200
      },
      {
        "src": "/images/brand/logo-reversed-2004.webp",
        "width": 2004
      }
    ]
  },
  "brand/logo": {
    "width": 2004,
    "height": 1468,
    "variants": [
      {
        "src": "/images/brand/logo-200.webp",
        "width": 200
      },
      {
        "src": "/images/brand/logo-2004.webp",
        "width": 2004
      }
    ]
  }
} as const satisfies Record<string, ImageEntry>;

export type ImageKey = keyof typeof images;
