// Post-build quality gate over the static export in out/ (runs after `next build`).
// Fails the build — and therefore the Netlify deploy — when a page regresses on
// the things the project directive and SEO constitution require:
//
//   • every indexable page: one <title>, a meta description, one <h1>, a
//     self-referencing canonical on SITE_URL, <html lang>; titles and
//     descriptions unique across pages
//   • noindex only on pages meant to be hidden
//   • internal links and image sources resolve to files in out/
//   • every <img> has alt text (may be empty for decoration) and width/height
//   • JSON-LD parses
//   • sitemap.xml lists exactly the indexable pages; robots.txt names it
//   • no template contamination or internal "CLIENT CONFIRMATION REQUIRED"
//     markers in any published HTML
//   • image weight budget
import { parse } from "node-html-parser";
import { readdir, readFile, stat } from "node:fs/promises";
import { join, relative } from "node:path";

const OUT = process.env.CHECK_DIR ?? new URL("../out/", import.meta.url).pathname;
const SITE_URL = (process.env.SITE_URL ?? process.env.URL ?? "https://itqanpharma.com").replace(/\/$/, "");

// Pages that are deliberately excluded from search.
const HIDDEN = new Set(["/404.html", "/404/", "/_not-found/", "/brand/", "/__forms.html", "/brand/Logo3D.html"]);
// Copied verbatim from the design handoff; not generated by the app.
const VERBATIM = new Set(["/brand/Logo3D.html"]);
const BANNED = [/optcare/i, /ophthalmolog/i, /eye surgery/i, /electrician/i, /house clean/i, /melbourne/i, /sample@example\.com/i, /lorem ipsum/i, /hostlin/i, /CLIENT CONFIRMATION REQUIRED/i];
const IMAGE_BUDGET = 450 * 1024;

const errors = [];
const fail = (page, msg) => errors.push(`${page}: ${msg}`);

async function walk(dir) {
  const files = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(path)));
    else files.push(path);
  }
  return files;
}

const files = await walk(OUT);
const exists = new Set(files.map((f) => "/" + relative(OUT, f)));

/** URL path → file in out/ (trailingSlash export: /x/ → /x/index.html). */
function resolves(path) {
  const clean = decodeURI(path.split(/[?#]/)[0]);
  if (clean.endsWith("/")) return exists.has(clean + "index.html");
  return exists.has(clean) || exists.has(clean + "/index.html") || exists.has(clean + ".html");
}

const toRoute = (file) => {
  const rel = "/" + relative(OUT, file);
  return rel.endsWith("/index.html") ? rel.slice(0, -"index.html".length) : rel;
};

const titles = new Map();
const descriptions = new Map();
const indexable = [];

for (const file of files.filter((f) => f.endsWith(".html"))) {
  const route = toRoute(file);
  const html = await readFile(file, "utf8");
  for (const pattern of BANNED) if (pattern.test(html)) fail(route, `contains banned text ${pattern}`);
  if (VERBATIM.has(route)) continue;

  const doc = parse(html);
  const robots = doc.querySelector('meta[name="robots"]')?.getAttribute("content") ?? "";
  const hidden = HIDDEN.has(route);
  if (/noindex/.test(robots) && !hidden) fail(route, "has noindex but is meant to be indexable");

  if (!hidden) {
    indexable.push(route);
    if (!doc.querySelector("html")?.getAttribute("lang")) fail(route, "missing <html lang>");
    const title = doc.querySelectorAll("title");
    if (title.length !== 1 || !title[0]?.text.trim()) fail(route, `expected one non-empty <title>, found ${title.length}`);
    else titles.set(title[0].text.trim(), [...(titles.get(title[0].text.trim()) ?? []), route]);
    const desc = doc.querySelector('meta[name="description"]')?.getAttribute("content")?.trim();
    if (!desc) fail(route, "missing meta description");
    else descriptions.set(desc, [...(descriptions.get(desc) ?? []), route]);
    const h1 = doc.querySelectorAll("h1");
    if (h1.length !== 1) fail(route, `expected one <h1>, found ${h1.length}`);
    const canonical = doc.querySelector('link[rel="canonical"]')?.getAttribute("href");
    if (canonical !== SITE_URL + route) fail(route, `canonical is ${canonical ?? "missing"}, expected ${SITE_URL + route}`);
    if (!doc.querySelector('meta[property="og:image"]')) fail(route, "missing og:image");
  }

  for (const a of doc.querySelectorAll("a[href]")) {
    const href = a.getAttribute("href") ?? "";
    if (href.startsWith("/") && !href.startsWith("//") && !resolves(href)) fail(route, `broken internal link ${href}`);
  }
  for (const img of doc.querySelectorAll("img")) {
    const src = img.getAttribute("src") ?? "";
    if (img.getAttribute("alt") === undefined) fail(route, `<img ${src}> has no alt attribute`);
    if (!img.getAttribute("width") || !img.getAttribute("height")) fail(route, `<img ${src}> has no width/height (layout shift)`);
    const sources = [src, ...(img.getAttribute("srcset") ?? img.getAttribute("srcSet") ?? "").split(",").map((s) => s.trim().split(/\s+/)[0] ?? "")];
    for (const s of sources) if (s.startsWith("/") && !resolves(s)) fail(route, `missing image file ${s}`);
  }
  for (const script of doc.querySelectorAll('script[type="application/ld+json"]')) {
    try {
      JSON.parse(script.text);
    } catch {
      fail(route, "JSON-LD does not parse");
    }
  }
}

for (const [title, routes] of titles) if (routes.length > 1) fail(routes.join(", "), `duplicate title "${title}"`);
for (const [desc, routes] of descriptions) if (routes.length > 1) fail(routes.join(", "), `duplicate description "${desc.slice(0, 60)}…"`);

// Sitemap must list exactly the indexable pages, on SITE_URL.
const sitemap = await readFile(join(OUT, "sitemap.xml"), "utf8").catch(() => "");
const listed = [...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1] ?? "");
for (const url of listed) {
  if (!url.startsWith(SITE_URL + "/")) fail("sitemap.xml", `URL not on ${SITE_URL}: ${url}`);
  const path = url.slice(SITE_URL.length);
  if (!indexable.includes(path)) fail("sitemap.xml", `lists ${path}, which is not an indexable page`);
}
for (const route of indexable) if (!listed.includes(SITE_URL + route)) fail("sitemap.xml", `missing ${route}`);
const robots = await readFile(join(OUT, "robots.txt"), "utf8").catch(() => "");
if (!robots.includes(`Sitemap: ${SITE_URL}/sitemap.xml`)) fail("robots.txt", "does not reference the sitemap");

for (const file of files.filter((f) => f.includes("/images/"))) {
  const { size } = await stat(file);
  if (size > IMAGE_BUDGET) fail("/" + relative(OUT, file), `image is ${(size / 1024).toFixed(0)} KB (budget ${IMAGE_BUDGET / 1024} KB)`);
}

if (errors.length) {
  console.error(`\nSite quality gate: ${errors.length} problem(s)\n  ${errors.join("\n  ")}\n`);
  process.exit(1);
}
console.log(`Site quality gate: ${indexable.length} indexable pages and ${listed.length} sitemap URLs checked on ${SITE_URL}; no problems.`);
