// Builds the site's image set from the official assets in the design handoff.
//
//   npm run images
//
// Reads  design_handoff_itqan_website/site/assets/**   (originals, never modified)
// Writes public/images/**                              (responsive WebP sets)
//        public/og.png, src/app/icon.png, src/app/apple-icon.png
//        public/brand/Logo3D.html (+ its scripts), copied verbatim
//        src/lib/images.generated.ts                   (typed manifest used by <Picture>)
//
// Packaging and logos are resized only, never cropped or retouched. Logos are
// encoded losslessly; photos and packaging use high-quality lossy WebP.
// Re-run this whenever an original asset changes, and commit the output.
import sharp from "sharp";
import { copyFile, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join, parse } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const SRC = join(ROOT, "design_handoff_itqan_website/site/assets");
const OUT = join(ROOT, "public/images");

// Target widths per group. A width larger than the original is skipped.
// Packaging is resized by its longest side so tall and wide boxes get the same treatment.
const GROUPS = {
  products: { widths: [400, 800, 1200], fit: "longest", quality: 85 },
  facility: { widths: [640, 1024, 1600, 2400], fit: "width", quality: 80 },
  // Lossless logos: downscaled copies compress worse than the original size (anti-aliased
  // edges), so only a small header size and the full size are produced.
  brand: { widths: [200, 2004], fit: "width", lossless: true },
};

const manifest = {};
await rm(OUT, { recursive: true, force: true });

for (const [group, cfg] of Object.entries(GROUPS)) {
  await mkdir(join(OUT, group), { recursive: true });
  for (const file of (await readdir(join(SRC, group))).sort()) {
    const name = parse(file).name;
    const input = join(SRC, group, file);
    const meta = await sharp(input).metadata();
    const longest = Math.max(meta.width, meta.height);
    const variants = [];
    const limit = cfg.fit === "longest" ? longest : meta.width;
    // Targets up to the original size, plus the original size itself when it
    // falls between two targets (e.g. a 741px source gets 400 and 741).
    const sizes = cfg.widths.filter((w) => w < limit);
    if (sizes.length < cfg.widths.length) sizes.push(limit);
    for (const size of sizes) {
      const resize = cfg.fit === "longest" ? { width: size, height: size, fit: "inside" } : { width: size };
      const out = join(OUT, group, `${name}-${size}.webp`);
      const info = await sharp(input)
        .resize({ ...resize, withoutEnlargement: true })
        .webp(cfg.lossless ? { lossless: true, effort: 6 } : { quality: cfg.quality, effort: 6, smartSubsample: true })
        .toFile(out);
      variants.push({ src: `/images/${group}/${name}-${size}.webp`, width: info.width, height: info.height, bytes: info.size });
    }
    const largest = variants[variants.length - 1];
    manifest[`${group}/${name}`] = { width: largest.width, height: largest.height, variants: variants.map(({ src, width }) => ({ src, width })) };
    console.log(`${group}/${file}`.padEnd(34), variants.map((v) => `${v.width}w ${(v.bytes / 1024).toFixed(0)}KB`).join("  "));
  }
}

// Favicons: the full logo centred on a transparent square, as the prototype used.
const logo = join(SRC, "brand/logo.png");
for (const [file, size] of [["src/app/icon.png", 256], ["src/app/apple-icon.png", 180]]) {
  const inner = Math.round(size * 0.92);
  const mark = await sharp(logo).resize({ width: inner, height: inner, fit: "inside" }).toBuffer();
  await sharp({ create: { width: size, height: size, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite([{ input: mark, gravity: "center" }])
    .png()
    .toFile(join(ROOT, file));
}

// Social preview card (1200x630): reversed logo on the ink ground used by the dark theme.
const card = await sharp(join(SRC, "brand/logo-reversed.png")).resize({ width: 620 }).toBuffer();
await sharp({ create: { width: 1200, height: 630, channels: 4, background: "#0e0a12" } })
  .composite([{ input: card, gravity: "center" }])
  .png()
  .toFile(join(ROOT, "public/og.png"));

// The designer's standalone 3D viewer/exporter for the brand sheet, copied verbatim
// with the relative paths it expects (/brand/Logo3D.html → ../shared, ../assets).
const TOOLS = join(ROOT, "design_handoff_itqan_website/site");
for (const [from, to] of [
  ["brand/Logo3D.html", "public/brand/Logo3D.html"],
  ["brand/three-d-stage.js", "public/brand/three-d-stage.js"],
  ["shared/logo-voxels.js", "public/shared/logo-voxels.js"],
  ["assets/brand/logo.png", "public/assets/brand/logo.png"],
]) {
  await mkdir(join(ROOT, parse(to).dir), { recursive: true });
  await copyFile(join(TOOLS, from), join(ROOT, to));
}

const ts = `// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
export type ImageVariant = { src: string; width: number };
export type ImageEntry = { width: number; height: number; variants: readonly ImageVariant[] };

export const images = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, ImageEntry>;

export type ImageKey = keyof typeof images;
`;
await writeFile(join(ROOT, "src/lib/images.generated.ts"), ts);
console.log(`\nWrote ${Object.keys(manifest).length} images to public/images and src/lib/images.generated.ts`);
